get:
  tags:
    -  Product
  summary: Get a product by ID
  description:  |
    Get a product by ID
  operationId: getProductById
  parameters:
    - name: productId
      in: path
      description: The ID of the product to retrieve
      required: true
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/v1/product.yaml"
    '400':
      description: Bad Request
    '404':
      description: Not Found
